KFold Cross Validation Python Tutorial
https://github.com/codebasics/py/blob/master/ML/12_KFold_Cross_Validation/12_k_fold.ipynb

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

#import the data
digits = load_digits()

In [3]:
from sklearn.model_selection import cross_val_score

In [4]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=10) #kfold = 10

array([0.91111111, 0.93888889, 0.89444444, 0.86666667, 0.94444444,
       0.97222222, 0.97777778, 0.94972067, 0.8603352 , 0.94413408])

In [6]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=10) #kfold = 10, default kernel = rbf/gaussian

array([0.43888889, 0.57777778, 0.46666667, 0.38888889, 0.47222222,
       0.4       , 0.50555556, 0.57541899, 0.55865922, 0.43575419])

In [7]:
cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target,cv=10) #kfold = 10

array([0.88333333, 0.97222222, 0.93333333, 0.87777778, 0.96111111,
       0.96666667, 0.97222222, 0.96648045, 0.93854749, 0.93854749])

From the result above, logistic regression is performing well on this data set. SVM is the worst but can improved using different kernel. We can also improve random forest using more dense forest.

In [8]:
cross_val_score(SVC(gamma='auto', kernel = 'linear'), digits.data, digits.target,cv=10) #kfold = 10

array([0.93888889, 0.99444444, 0.93333333, 0.94444444, 0.96111111,
       0.98888889, 0.96666667, 0.97765363, 0.93296089, 0.96648045])

In [9]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data, digits.target,cv=10) #kfold = 10

array([0.90555556, 0.96666667, 0.95555556, 0.91666667, 0.95555556,
       0.97222222, 0.97222222, 0.96089385, 0.92178771, 0.9273743 ])